language: ruby
rvm:
  - 2.2.0
  - 2.1.5
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx
matrix:
  include:
    - rvm: 1.8.7
      gemfile: Gemfile.travis18
    - rvm: ree
      gemfile: Gemfile.travis18
branches:
  only:
    - master
git:
  depth: 150
bundler_args: --without development
script: bundle exec rspec -fdoc
gemfile: Gemfile.travis
addons:
  code_climate:
    repo_token: 2877e253fb18735180e9c3f5faf075c3190b63fd720dc2a282751a4d50290fa8
